### PR TITLE
wip feat: Add support for calling an external policy agent to control authorizing field level access for GraphQL requests. Fixes #33

### LINKED ISSUE #33: A plugin that runs before every request is received to GW
We're running our Graphql services in production using a micro services approach. We're using Hasura to combine everything together but we would like a gateway which we can configure and add our complex authorization to the queries/mutations before they're run.

Is this something `graphql-gw` can do? e.g flow:

```
-> Clients call query getUsers
-> GW receives request
-> GW runs beforeReq plugin
-> Plugin runs our code
-> Our code calls to our auth service to determine if current user is authorized to do this
-> If not, throws error without accessing upstream graphs
-> If yes, forward request to upstream graphs
-> Response to clients
```

### PR DESCRIPTION
**Pull request by chirino**

### CODE REVIEW

**Comment by chirino** [comment]
@wtrocki this is what I have so far.  I went with a GRPC interface between the gateway and the policy server to improve performance.  [main.go](https://github.com/chirino/graphql-gw/blob/2f76a9719bef42727eea41d9a88eb47c0d00f2c9/internal/gateway/examples/policyagent/main.go) is an example implementation.

If pushed to, I think we can also build a REST based interface like I mentioned in #33 but I figured folks would want this to be as fast as possible.

**Comment by wtrocki** [comment]
Usage of gRPC will mean that when using keycloak or any other SSO we will need extra server that will expose gRPC? I see some experimental extensions for keycloak itself: https://github.com/openstandia/keycloak-grpc

**Comment by wtrocki** [comment]
Ignore my comment. I see how this works based on https://www.openpolicyagent.org/docs/latest/

**Comment by wtrocki** [comment]
I think I will need some basic docs on how to run sample service. Unit tests coveting the basic use case so it is best to merge it and get people's feedback as well (with some documentation)

**Comment by chirino** [comment]
@wtrocki heres a little more advanced example:
[3scale-graphql-pa](https://github.com/chirino/3scale-graphql-pa) implements a policy agent that uses 3scale for auth and per field access control.

And here's a kube deployment config that deploys the gateway and the policy agent in a single pod so that they are working together:
https://github.com/chirino/3scale-graphql-pa/blob/master/kubernetes/install.yaml

**Comment by wtrocki** [comment]
Really impressive work!

**Pull request merged**
